{
 "title": "cAdvisor",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "cAdvisorCPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_cpu_usage_seconds_total{name=\"cadvisor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App1CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_cpu_usage_seconds_total{name=\"app1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App2CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_cpu_usage_seconds_total{name=\"app2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PrometheusCPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(container_cpu_usage_seconds_total{name=\"prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cAdvisorMem",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_memory_rss{name=\"cadvisor\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TotalCPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{cpu=\"total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App1NetIO",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"app1\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App2Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"app2\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}