{
 "title": "K8sClusterDetails",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "NodeName",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_status_replicas,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MemoryOverview",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\",container=\"controller\"}",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\",container=\"etcd\"}",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\",container=\"coredns\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "ContainerMemoryURequests",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"memory\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "ContainerCPURequests",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\",resource=\"cpu\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "TotalContainer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=\"default\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RunningContainer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TerminatedContainer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ContainerDetails", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "NodesDetails",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "TotalNodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_info{node=\"$node\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "UnavailableNodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable{node=\"$node\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OverView",
     "type": "stat",
     "gridPos": { "h": 4, "w": 16, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_info{node=\"$node\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(kube_node_spec_unschedulable{node=\"$node\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PodDetails",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "RunningPods",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\",phase=\"Running\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PendingPods",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\",phase=\"Pending\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "FailedPods",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\",phase=\"Failed\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SucceededPods",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\",phase=\"Succeeded\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "DeploymentDetails",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "DeploymentReplicas",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "UpdatedReplicas",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=\"$namespace\"})",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "UnAvailableReplicas",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"$namespace\"})"
      }
     ]
    }
   ]
  }
 ]
}