{
 "title": "NodeDetails",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "InstanceName",
    "query": {
     "query": "label_values(node_memory_MemAvailable_bytes,instance)"
    }
   },
   {
    "name": "job",
    "label": "JobName",
    "query": {
     "query": "label_values(node_cpu_seconds_total,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPUUtilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{job=\"$job\", instance=\"$instance\", mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "MemoryUtilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\", job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$instance\", job=\"$job\"} - node_memory_Buffers_bytes{instance=\"$instance\", job=\"$job\"} - node_memory_Cached_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RootDisk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"$job\",instance=\"$instance\",device!=\"tmpfs\",fstype=\"ext4\",mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "TotalMemory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BootDisk",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\", job=\"$job\", device=\"/dev/sda1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\", job=\"$job\"} - node_boot_time_seconds{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "NetworkReceived&Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$instance\", job=\"$job\"}[5m])",
     "legendFormat": "{{device}} Received"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$instance\",job=\"$job\"}[5m])",
     "legendFormat": "{{device}} Transmit"
    }
   ]
  },
  {
   "title": "Disk I/O Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads Compleated"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes Completed"
    }
   ]
  },
  {
   "title": "PowerSupply",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_power_supply_online{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU-Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(cpu) (node_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}))"
    }
   ]
  },
  {
   "title": "DiskSpaceUsage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance\",job=\"$job\",device!~\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$instance\",job=\"$job\",device!~\"rootfs\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "FreeSpace for /dev/sda2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sda2\",instance=\"localhost:9100\",job=\"K8s\",mountpoint=\"/\"}",
     "legendFormat": "{{device}} FreeSpace"
    }
   ]
  }
 ]
}